apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kuberfirstservice-be81"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kuberfirstservice-be81"
  template:
    metadata:
      labels:
        app: "kuberfirstservice-be81"
    spec:
      containers:
        - name: "kuberfirstservice-be81"
          image: "containerforkuber01.azurecr.io/kuberfirstservice"
          ports:
          - containerPort: 80