apiVersion: v1
kind: Service
metadata:
    name: "kuberfirstservice-be81"
    labels:
        app: "kuberfirstservice-be81"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kuberfirstservice-be81"