on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containerforkuber01.azurecr.io
        username: ${{ secrets.acr_containerforkuber01_username }}
        password: ${{ secrets.acr_containerforkuber01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/OrderItemWebAPI" -f  "OrderItemWebAPI/Dockerfile" -t containerforkuber01.azurecr.io/kuberfirstservice:${{ github.sha }} --label dockerfile-path=OrderItemWebAPI/Dockerfile
        docker push containerforkuber01.azurecr.io/kuberfirstservice:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kuberfirstservice_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kuberfirstservicea5ee | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kuberfirstservicea5ee`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kuberfirstservicea5ee
        container-registry-url: containerforkuber01.azurecr.io
        container-registry-username: ${{ secrets.acr_containerforkuber01_username }}
        container-registry-password: ${{ secrets.acr_containerforkuber01_password }}
        secret-name: kuberfirstsedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kuberfirstservicea5ee
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          containerforkuber01.azurecr.io/kuberfirstservice:${{ github.sha }}
        imagepullsecrets: |
          kuberfirstsedockerauth
